### ISSUE TITLE
compute_gradients + apply_gradients vs. minimize

### ISSUE THREAD

**Issue by winni2k** [ctmakro/DCGAN-Keras#2]
I was wondering if there is a particular reason why the gradients of the generator and discriminator are computed and applied in two steps instead of using `minimize`?

See:  https://github.com/ctmakro/DCGAN-Keras/blob/master/lets_gan.py#L163

**Comment by ctmakro** [comment]
@wkretzsch just to clarify things a little bit. It would be fine to use minimize().

**Comment by winni2k** [comment]
Cheers, thanks for your time.
